# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				axolotl = true
				egg = true
				zoglin = true
				allay = true
				llama = true
				bat = true
				husk = true
				camel = true
				experience_bottle = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				giant = true
				drowned = true
				item = true
				goat = true
				vindicator = true
				horse = true
				llama_spit = true
				glow_item_frame = false
				snowball = true
				parrot = true
				creeper = true
				lightning_bolt = true
				evoker_fangs = true
				tropical_fish = true
				chest_minecart = true
				slime = true
				pillager = true
				area_effect_cloud = true
				blaze = true
				piglin = true
				end_crystal = true
				endermite = true
				zombie = true
				ender_pearl = true
				item_display = true
				guardian = true
				fireball = true
				illusioner = true
				eye_of_ender = true
				wolf = true
				zombie_villager = true
				tnt_minecart = true
				block_display = true
				elder_guardian = true
				chest_boat = true
				boat = true
				small_fireball = true
				strider = true
				cave_spider = true
				cod = true
				witch = true
				snow_golem = true
				spider = true
				command_block_minecart = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				frog = true
				hoglin = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				turtle = true
				salmon = true
				wandering_trader = true
				wither_skeleton = true
				vex = true
				piglin_brute = true
				ocelot = true
				furnace_minecart = true
				item_frame = true
				phantom = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				glow_squid = true
				warden = true
				squid = true
				enderman = true
				dragon_fireball = true
				chicken = true
				trader_llama = true
				donkey = true
				fox = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				skeleton_horse = true
				polar_bear = true
				hopper_minecart = true
				falling_block = true
				painting = true
				interaction = true

			[light_sources.settings.entities.spell_engine]
				spell_projectile = true
				spell_area_effect = true

			[light_sources.settings.entities.niftycarts]
				plow = true
				supply_cart = true
				postilion = true
				hand_cart = true
				animal_cart = true

			[light_sources.settings.entities.illagerinvasion]
				sorcerer = true
				provoker = true
				archivist = true
				inquisitor = true
				basher = true
				invoker = true
				marauder = true

			[light_sources.settings.entities.naturalist]
				deer = true
				snail = true
				rhino = true
				bluejay = true
				snake = true
				boar = true
				robin = true
				tortoise = true
				butterfly = true
				duck = true
				bear = true
				sparrow = true
				lizard = true
				zebra = true
				rattlesnake = true
				canary = true
				firefly = true
				coral_snake = true
				cardinal = true
				lion = true
				vulture = true
				bass = true
				giraffe = true
				elephant = true
				finch = true

			[light_sources.settings.entities.majruszsdifficulty]
				illusioner = true
				cursed_armor = true
				cerberus = true
				tank = true

			[light_sources.settings.entities.mcdar]
				enchanted_blue_sheep = true
				golem_kit_golem = true

			[light_sources.settings.entities.botania]
				pixie = true
				mana_burst = true
				vine_ball = true
				magic_missile = true
				doppleganger = true
				flame_ring = true
				magic_landmine = true
				babylon_weapon = true
				thorn_chakram = true
				player_mover = true
				corporea_spark = true

			[light_sources.settings.entities.betternether]
				naga_projectile = true
				firefly = true
				hydrogen_jellyfish = true
				skull = true
				jungle_skeleton = true
				naga = true

			[light_sources.settings.entities.immersive_aircraft]
				gyrodyne = true
				biplane = true

			[light_sources.settings.entities.create]
				carriage_contraption = true
				stationary_contraption = true
				super_glue = true
				potato_projectile = true

			[light_sources.settings.entities.origins]
				enderian_pearl = true

			[light_sources.settings.entities.travelersbackpack]
				backpack = true

			[light_sources.settings.entities.creeperoverhaul]
				bamboo_creeper = true
				jungle_creeper = true
				cave_creeper = true
				beach_creeper = true
				savannah_creeper = true
				hills_creeper = true
				spruce_creeper = true
				snowy_creeper = true
				badlands_creeper = true
				ocean_creeper = true
				dark_oak_creeper = true
				desert_creeper = true
				dripstone_creeper = true

			[light_sources.settings.entities.deeperdarker]
				shattered = true
				sludge = true
				shriek_worm = true
				sculk_centipede = true
				sculk_leech = true
				sculk_snapper = true

			[light_sources.settings.entities.mcwfurnitures]
				chair_entity = true

			[light_sources.settings.entities.railways]
				conductor = true

			[light_sources.settings.entities.hauntedharvest]
				splattered_egg = true

			[light_sources.settings.entities.minecells]
				grenadier = true
				leaping_zombie = true
				sweeper = true
				conjunctivius_obelisk = true
				protector = true
				conjunctivius_projectile = true
				conjunctivius = true
				mutated_bat = true
				elite_obelisk = true
				magic_orb = true
				concierge_obelisk = true
				undead_archer = true
				custom_arrow = true
				buzzcutter = true
				shieldbearer = true
				elevator = true
				inquisitor = true
				runner = true
				shockwave_placer = true
				sewers_tentacle = true
				concierge = true

			[light_sources.settings.entities.beansbackpacks]
				backpack = true

			[light_sources.settings.entities.dummmmmmy]
				target_dummy = true

			[light_sources.settings.entities.supplementaries]
				red_merchant = true
				hat_stand = true
				rope_arrow = true

			[light_sources.settings.entities.friendsandfoes]
				glare = true
				copper_golem = true
				player_illusion = true
				moobloom = true
				mauler = true
				crab = true
				rascal = true

			[light_sources.settings.entities.aquamirae]
				anglerfish = true
				tortured_soul = true
				maze_mother = true
				spinefish = true

			[light_sources.settings.entities.tinyskeletons]
				baby_stray = true
				baby_wither_skeleton = true
				baby_skeleton = true

