debug = false
disable_crowdin = false
check_for_updates = true

[activations.b883cd09-ef51-3ee0-b72f-28aba1e5c184]
toggle = true
type = "PUSH_TO_TALK"
[activations.4aec07ba-d109-3345-9a0a-92022a116cd0]
toggle = false
type = "VOICE"
[[key_bindings]]
name = "key.plasmovoice.general.mute_microphone"
any_context = false
category = "key.plasmovoice.general"

[[key_bindings.keys]]
code = 266
type = "KEYSYM"

[[key_bindings]]
name = "key.plasmovoice.general.disable_voice"
any_context = false
category = "key.plasmovoice.general"

[[key_bindings.keys]]
code = 267
type = "KEYSYM"

[[key_bindings]]
keys = []
name = "key.plasmovoice.general.action"
any_context = false
category = "key.plasmovoice.general"

[[key_bindings]]
name = "key.plasmovoice.groups.ptt"
any_context = true
category = "hidden"

[[key_bindings.keys]]
code = 342
type = "KEYSYM"

[[key_bindings]]
name = "key.plasmovoice.broadcast.ptt"
any_context = true
category = "hidden"

[[key_bindings.keys]]
code = 348
type = "KEYSYM"

[[key_bindings]]
name = "key.plasmovoice.priority.ptt"
any_context = true
category = "hidden"

[[key_bindings.keys]]
code = 345
type = "KEYSYM"

[[key_bindings]]
name = "key.plasmovoice.whisper.ptt"
any_context = true
category = "hidden"

[[key_bindings.keys]]
code = 346
type = "KEYSYM"



[voice]
disabled = false
microphone_disabled = false
activation_threshold = -55.0
input_device = ""
output_device = ""
disable_input_device = false
use_javax_input = false
microphone_volume = 1.0
noise_suppression = true
volume = 1.0
compressor_limiter = true
sound_occlusion = false
directional_sources = true
hrtf = false
stereo_capture = true

[voice.volumes.broadcast]
volume = 1.0
[voice.volumes.proximity]
volume = 1.0
[voice.volumes.groups]
volume = 1.0
[voice.volumes.whisper]
volume = 1.0
[voice.volumes.priority]
volume = 1.0

[advanced]
visualize_voice_distance = true
visualize_voice_distance_on_join = false
compressor_threshold = -10
limiter_threshold = -6
directional_sources_angle = 145
stereo_sources_to_mono = false
panning = true
camera_sound_listener = true
exponential_volume_slider = true
exponential_distance_gain = true
jitter_packet_delay = 3
al_playback_buffers = 5

[overlay]
show_activation_icon = true
activation_icon_position = "BOTTOM_CENTER"
show_source_icons = 0
show_static_source_icons = true
overlay_enabled = true
overlay_position = "TOP_LEFT"
overlay_style = "NAME_SKIN"

[overlay.source_states]
broadcast = "OFF"
proximity = "OFF"
groups = "WHEN_TALKING"
whisper = "OFF"
priority = "OFF"
